---
- name: Create a change request on Service now
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Create a change request
    snow_record:
      state: present
      table: change_request
      username: admin
      password: cusEWWG5j7kI
      instance: dev71090
      data:
        severity: 2
        priority: 2
        category: Software
        short_description: "Application Sucessfuly deployed on Tomcat"
        description: "Sample Java Application deployment is successfully completed"
    register: change

  - debug: 
      var: change.record
      verbosity: 3
