---
- name: Register an incident on SN
  hosts: all
  tasks:
  - name: latest version of pip installed
    yum:
     name: pip3
     state: latest
  - name: Create a incident
    snow_record:
      state: present
      username: admin
      password: cbOheOVW8pA1
      instance: dev110714
      data:
        severity: 3
        priority: 2
        short_description: "Apache failed to install"
        description: "Apache failed to install on {{ ansible_all_ipv4_addresses }}"
        category: Software
    register: new_incident

  - debug: 
      var: new_incident.record
