---
- name: Register an incident on SN
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Create a incident
    snow_record:
      state: present
      username: admin
      password: be3HUhK8NljY
      instance: dev116580
      data:
        severity: 3
        priority: 2
        short_description: "Apache failed to install"
        description: "Apache failed to install on {{ public_ip }}"
        category: Software

  - debug: 
      var: new_incident.record
