---
- name: Register an incident on SN
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Create a incident
    snow_record:
      state: present
      username: admin
      password: cbOheOVW8pA1
      instance: dev110714
      data:
        severity: 3
        priority: 2
        short_description: "Application Sucessfuly deployed on Tomcat"
        description: "Access Application on http://192.168.56.104:8080/sample1/"
        category: Software
    register: new_incident

  - debug: 
      var: new_incident.record
